# COMP4220: Machine Learning, Fall 2020
# Assignment 1 Solution
# Due: Monday, September 14th, 10:00 PM

For the future homeworks, Please submit just one pdf file.

**No late submission was applied for HW1. Please make sure to upload your file.pdf before due date/time for your future submissions.


1. What are the two most common supervised tasks? 

 The two most common supervised tasks are regression and classification. 

2. What are four common unsupervised tasks? 

Common unsupervised tasks include clustering, visualization, dimensionality reduction, and association rule learning. 

3. What is the difference between a model parameter and a learning algorithm’s hyperparameter? 

 A model has one or more model parameters that determine what it will predict given a new instance (e.g., the slope of a linear model). A learning algorithm tries to find optimal values for these parameters such that the model generalizes well to new instances. A hyperparameter is a parameter of the learning algorithm itself, not of the model (e.g., the amount of regularization to apply

4. What is a test set, and why would you want to use it? 

A test set is used to estimate the generalization error that a model will make on new instances, before the model is launched in production.


5. What is the purpose of a validation set? 

A validation set is used to compare models. It makes it possible to select the best model and tune the hyperparameters. 

6. What can go wrong if you tune hyperparameters using the test set? 

 If you tune hyperparameters using the test set, you risk overfitting the test set, and the generalization error you measure will be optimistic (you may launch a model that performs worse than you expect).


7. Programming assignment (download the folder hw1problem7 from blackboard).


In [4]:
import numpy as np

Task: create a normalized form of the following data set (accessed through UCI Machine Learning Repository) whose values range exactly between 0 and 1 so that the minimum has value 0 and maximum has value 1.

In [5]:
# Load the data 
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
data = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0])

In [6]:
# Find the maximum and minimum values of data and print them: Smax and Smin
Smax, Smin = np.max(data),np.min(data)
print(Smax, Smin)

7.9 4.3


In [7]:
# Use (x - Smin)/(Smax - Smin) to normalize the data 
data_preprocessed = (data-Smin)/(Smax-Smin)
print(data_preprocessed)

[0.22222222 0.16666667 0.11111111 0.08333333 0.19444444 0.30555556
 0.08333333 0.19444444 0.02777778 0.16666667 0.30555556 0.13888889
 0.13888889 0.         0.41666667 0.38888889 0.30555556 0.22222222
 0.38888889 0.22222222 0.30555556 0.22222222 0.08333333 0.22222222
 0.13888889 0.19444444 0.19444444 0.25       0.25       0.11111111
 0.13888889 0.30555556 0.25       0.33333333 0.16666667 0.19444444
 0.33333333 0.16666667 0.02777778 0.22222222 0.19444444 0.05555556
 0.02777778 0.19444444 0.22222222 0.13888889 0.22222222 0.08333333
 0.27777778 0.19444444 0.75       0.58333333 0.72222222 0.33333333
 0.61111111 0.38888889 0.55555556 0.16666667 0.63888889 0.25
 0.19444444 0.44444444 0.47222222 0.5        0.36111111 0.66666667
 0.36111111 0.41666667 0.52777778 0.36111111 0.44444444 0.5
 0.55555556 0.5        0.58333333 0.63888889 0.69444444 0.66666667
 0.47222222 0.38888889 0.33333333 0.33333333 0.41666667 0.47222222
 0.30555556 0.47222222 0.66666667 0.55555556 0.36111111 0.33333333
 0.33333

After writing your own code, we like to confirm that built-in functions in Scikit-Learn provide identical results. There are at least two techniques for normalizing the data using *sklearn.preprocessing*.

In [8]:
# Technique 1: using minmax_scale 
from sklearn.preprocessing import minmax_scale
data_preprocessed2 = minmax_scale(data)
print(data_preprocessed2)

[0.22222222 0.16666667 0.11111111 0.08333333 0.19444444 0.30555556
 0.08333333 0.19444444 0.02777778 0.16666667 0.30555556 0.13888889
 0.13888889 0.         0.41666667 0.38888889 0.30555556 0.22222222
 0.38888889 0.22222222 0.30555556 0.22222222 0.08333333 0.22222222
 0.13888889 0.19444444 0.19444444 0.25       0.25       0.11111111
 0.13888889 0.30555556 0.25       0.33333333 0.16666667 0.19444444
 0.33333333 0.16666667 0.02777778 0.22222222 0.19444444 0.05555556
 0.02777778 0.19444444 0.22222222 0.13888889 0.22222222 0.08333333
 0.27777778 0.19444444 0.75       0.58333333 0.72222222 0.33333333
 0.61111111 0.38888889 0.55555556 0.16666667 0.63888889 0.25
 0.19444444 0.44444444 0.47222222 0.5        0.36111111 0.66666667
 0.36111111 0.41666667 0.52777778 0.36111111 0.44444444 0.5
 0.55555556 0.5        0.58333333 0.63888889 0.69444444 0.66666667
 0.47222222 0.38888889 0.33333333 0.33333333 0.41666667 0.47222222
 0.30555556 0.47222222 0.66666667 0.55555556 0.36111111 0.33333333
 0.33333

In [37]:
# Technique 2: using the``Transformer`` API MinMaxScaler 
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
data_preprocessed3 = scaler.fit_transform(data)

ValueError: ignored

You probably got an error message. Please read this message and see how you can fix it. 
It looks like this error has to do something with the shape of *data* (1D vs 2D).
Please reshape *data* and make sure that the final normalized version has the same shape as *data_preprocessed* above. 

In [76]:
# Technique 2: using the``Transformer`` API MinMaxScaler 
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
data_preprocessed3 = scaler.fit_transform(data.reshape(-1,1)).reshape(-1,6)
print(data_preprocessed3)

[[0.22222222 0.16666667 0.11111111 0.08333333 0.19444444 0.30555556]
 [0.08333333 0.19444444 0.02777778 0.16666667 0.30555556 0.13888889]
 [0.13888889 0.         0.41666667 0.38888889 0.30555556 0.22222222]
 [0.38888889 0.22222222 0.30555556 0.22222222 0.08333333 0.22222222]
 [0.13888889 0.19444444 0.19444444 0.25       0.25       0.11111111]
 [0.13888889 0.30555556 0.25       0.33333333 0.16666667 0.19444444]
 [0.33333333 0.16666667 0.02777778 0.22222222 0.19444444 0.05555556]
 [0.02777778 0.19444444 0.22222222 0.13888889 0.22222222 0.08333333]
 [0.27777778 0.19444444 0.75       0.58333333 0.72222222 0.33333333]
 [0.61111111 0.38888889 0.55555556 0.16666667 0.63888889 0.25      ]
 [0.19444444 0.44444444 0.47222222 0.5        0.36111111 0.66666667]
 [0.36111111 0.41666667 0.52777778 0.36111111 0.44444444 0.5       ]
 [0.55555556 0.5        0.58333333 0.63888889 0.69444444 0.66666667]
 [0.47222222 0.38888889 0.33333333 0.33333333 0.41666667 0.47222222]
 [0.30555556 0.47222222 0.66666667